# Generated by Django 6.0.1 on 2026-02-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_stripe_payment_url_user_stripe_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
    ]
